### ISSUE TITLE
Globalize is not defined error while including dev extreme 

### ISSUE THREAD

**Issue by vineeth91** [DevExpress/bower-devextreme#1]
Uncaught ReferenceError: Globalize is not defined(anonymous function) @ dx.all.js:9(anonymous function)

**Comment by kaatula** [comment]
Would you please describe the issue in greater detail?

**Comment by vineeth91** [comment]
Now the issue with Globalize is fixed,now the problem is 
Uncaught Error: [$injector:modulerr] Failed to instantiate module dndApp due to:
Error: [$injector:modulerr] Failed to instantiate module dx due to:
Error: [$compile:baddir] Directive name 'DOMComponent' is invalid. The first character must be a lowercase letter

I just wanted to know which version of angularjs is supported by devextreme, currently  we are using 1.3.0

**Comment by kaatula** [comment]
I'm glad that you resolved your issue with Globalize.
Current version of DevExtreme (15.1.4) [supports AngularJS 1.2.\* and 1.3.*](http://js.devexpress.com/Documentation/Guide/Common/3rd-Party_Libraries_and_Frameworks_Integration/#Data_Binding_and_SPA_Frameworks)
