### ISSUE TITLE
jquery-1.11.3

### ISSUE THREAD

**Issue by ccodling** [DevExpress/bower-devextreme#10]
In the bower.json file there there is a dependency that is listed as:
 "jquery-1.11.3":  http://code.jquery.com/jquery-1.11.3.js"  We recently implemented some new web web filtering software across our company and it seems that this dependency as listed does not work unless it is secure.  I can get the library separately if I use https: in the URL instead of http:.

I can work around this, but wanted to ask why this is needed as a dependency when the bower.json file already lists jquery 2.1.4?  Is this something that can be removed or at least changed to https?
Thank you,
Cory Codling
NAVEX Global Inc.

**Comment by San4es** [comment]
Hi,

Fixed since https://github.com/DevExpress/bower-devextreme/commit/b7b0daafa391e6174af29e04ec03d825d60e845c.
