### ISSUE TITLE
Trying to use datasource i get undefinied error.

### ISSUE THREAD

**Issue by nrubiano** [DevExpress/bower-devextreme#11]
I'm using DevExtreme Version 16.1.4, but after update to that version, i get the following error.

![image](https://cloud.githubusercontent.com/assets/17432958/16321387/2bafb9d8-3962-11e6-8c7f-78b9ccd5635e.png)

but when i return to 15.2.10, the error disappear, any suggestions?

**Comment by Mehul** [comment]
Without more context, it's hard to tell but take a look at the v16.1 docs on datasource which contains code samples which may help you:
http://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/?search=datasource&version=16_1&approach=Knockout
