### ISSUE TITLE
DevExtreme Complete not @types

### ISSUE THREAD

**Issue by generik0** [DevExpress/bower-devextreme#16]
Hi

If this is "DevExtreme Complete" where are tjhe @types?

**Comment by San4es** [comment]
Hi,
This repo is for distribution of the DevExtreme product with Bower. Are you are using DevExtreme via Bower or Npm?

**Comment by San4es** [comment]
This issue is closed due to inactivity. In case of any questions regarding our product, please refer to our [Support Center](https://www.devexpress.com/Support/Center).
