### ISSUE TITLE
devextreme 19.2.x support

### ISSUE THREAD

**Issue by JanLorenz77** [DevExpress/bower-devextreme#17]
What ist with devextreme 19.2.x support ?

**Comment by BingoRUS** [comment]
As you can find [here](https://bower.io/blog/2017/how-to-migrate-away-from-bower/), Bower is deprecated and Bower creators recommend using other package managers. That is why we did not publish the 19.2 version using Bower. DevExtreme is available via [npm](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/npm_Package/) and [Yarn](https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/npm_Package/#Using_Yarn). If you cannot migrate to one of them, please describe the issue in greater detail.
