### ISSUE TITLE
17.1.17 Tag Has 19.1.11 Source Code

### ISSUE THREAD

**Issue by timlajaunie** [DevExpress/bower-devextreme#18]
We were targeting version ~17.1.6 which caused Bower to pull the latest revision (17.1.17), and we were surprised to see source files with a 19.1.11 version.

Please see [https://github.com/DevExpress/bower-devextreme/tree/17.1.17](https://github.com/DevExpress/bower-devextreme/tree/17.1.17)

It seems the 17.1.17 tag was applied to the incorrect source tree.

**Comment by babich-a** [comment]
Hi @timlajaunie . Thank you for your report. We have updated the wrong tags. BTW, Bower is in [maintenance mode now](https://community.devexpress.com/blogs/javascript/archive/2020/06/05/devexpress-bower-packages-are-discontinued.aspx). It is still available but is no longer considered a dependency manager of choice by modern web projects.
