### ISSUE TITLE
How to use DevExtreme Web bundle only?

### ISSUE THREAD

**Issue by disharmonized** [DevExpress/bower-devextreme#3]
I am planning to buy only DevExtreme Web bundle, how can i use it with bower?

**Comment by BingoRUS** [comment]
Hi disharmonized!
 
We now provide only the DevExtreme Complete bower package. It's impossible to use it with a DevExtreme Web license. However, we're working to add the DevExtreme Web bower package soon.

**Comment by babich-a** [comment]
https://github.com/DevExpress/bower-devextreme-web

**Comment by disharmonized** [comment]
Thanks!
