### ISSUE TITLE
Include pagination or virtual scrolling in the dxPivotGrid

### ISSUE THREAD

**Issue by nobjr** [DevExpress/bower-devextreme#4]
Hi,

We have serious performance browser problems in the Chrome and Firefox with dxPivotGrid while testing the trial version with huge data (millions of lines).

There is something in the future versions for treat this problem: pagination, virtual scrolling or other?

Thanks in advance for any help you are able to provide.

P.S.: We are interest in the acquire comercial license, but browser performance issues is very critical for us...

**Comment by babich-a** [comment]
We have plans to improve the dxPivotGrid performance to work with large volumes of data.

**Comment by babich-a** [comment]
Starting with 15.2, you can enable the virtual scrolling mode
https://www.devexpress.com/Support/Center/Question/Details/T276967
