### ISSUE TITLE
Using devextreme bower package in an asp.net core 1.0 RC2 application, the app does not compile

### ISSUE THREAD

**Issue by Se3ker** [DevExpress/bower-devextreme#9]
When using devextreme bower package in an asp.net core 1.0 RC2 application, the app does not compile.

It fails in globalize dependency, which requires System.Web

**Comment by AlekseyMartynov** [comment]
@Se3ker we'll process this issue in the context of the TagHelpers ticket https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/issues/28
